### PR TITLE
Integration of New Micrometa App Version

### PR DESCRIPTION
**Pull request by utku-ozturk**
A new version Micro Meta App has just released. We worked w/ Alex (UMass) together to integrate the new version into the portal. Here is the most recent configuration: http://fourfront-hotseat.9wzadzju3p.us-east-1.elasticbeanstalk.com/microscope-configurations/2b814fcb-a2e3-4354-a381-4241deba303e/

The major feature is snap-in-place of components while dragged onto canvas: ([screencast](https://i.gyazo.com/ed9fdb1cd5d99cc1866f7f402bed243b.gif))

And Caterina(UMass)'s message about the new release:

> 
> Release Micro Meta App 0.28.3-a1, implements significant upgrades to the user experience, including SNAP-IN-PLACE and several bug-fixes. However note that Micro Meta App 0.28.3-a1 implements the version of the 4DN-OME extension that was published in December 2019 (https://arxiv.org/abs/1910.11370).
> 
> Please download Micro Meta App 0.28.3-a1 from this drop-box link:
> https://www.dropbox.com/sh/lvclm6y3653z8lz/AADKo4TqtCSnCLujYjvI7gPSa?dl=
> Please find instructions on how to download Micro-Meta App from DropBox here
> https://docs.google.com/document/d/14DI02_0WGiqcLNwjl3QXPvjwEcvM7I3X2VB_CEw7upo/edit# 
> Please find full documentation and step-by-step instructions here:
> https://micrometaapp-docs.readthedocs.io/en/latest/index.html 
> Finally let me know if you are also interested in testing the OMERO.plugin version of Micro-Meta App and I can send you further instructions.

Screen Shot 2020-09-24 at 02 18 40

### CODE REVIEW

**Comment by j1z0** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/encoded/static/components/item-pages/MicroscopeConfigurationView.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/4dn/fourfront/pullRequest?prid=6227347&bid=20294570)

**Review by alexkb0009 — APPROVED** [review]
Looks good!

_My Outdated Comment:_

> Not sure if this is possible now (since existing code uses window.fetch for some reason or other... maybe CORI security or something) but in future would consider maybe changing to use [`ajax.promise`](https://github.com/4dn-dcic/shared-portal-components/blob/master/src/components/util/ajax.js#L75-L118) instead of `window.fetch` perhaps for consistency with rest/most of app using that or ajax.load and (less of an issue nowadays:) as some older browsers may not support window.fetch.

**Edit:**
I think I was trying to use ajax.promise before though and couldn't now that think back to it... I think loading the schemas from github had something to do with it. Maybe it's just matter of setting appropriate headers when using ajax.promise... idk. Random stuff to consider later I guess... not sure where final place of schemas will be anyways (maybe our server/domain even, maybe npm/unpkgd, idk), etc.

**Comment by j1z0** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/encoded/static/components/item-pages/MicroscopeConfigurationView.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/4dn/fourfront/pullRequest?prid=6227347&bid=20294570)

**Comment by j1z0** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/encoded/static/components/item-pages/MicroscopeConfigurationView.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/4dn/fourfront/pullRequest?prid=6227347&bid=20294570)

**Pull request merged**
