### PR TITLE
Small fixes to blue/green deployment, including better modularity via dcicutils.env_utils

### PR DESCRIPTION
**Pull request by netsettler**
Miscellaneous small changes related to deployment:

* Add a `blue.ini` and `green.ini` init files that set an appropriate mirror environment just in case, although other changes in this PR (in particular, importing the latest `dcicutils 0.12.0`) may obviate the need for that.
* Update `pyproject.toml` to depend on `dcicutils = ">=0.12.0,<1"` and `dcicsnovault = "^2.1.1"`, then updated `poetry.lock`. Also, remove `get_mirror_env` definition and related constants because they're moved to `dcicutils.env_utils`.
* In `src/encoded/commands/create_mapping_on_deploy.py`, use `is_test_env`, `is_hotseat_env`, `guess_mirror_env`, `is_stg_or_prd_env` from `dcicutils.env_utils`. Various constants are moved away to `.env_utils`, too, and do not need to be referenced here any longer.
* Fix tests relevant to previous stuff, though a lot of the heavy lifting for testing is done in `dcicutils` now.

Opportunistic:

* Add a `Makefile` with some basic commands similar to what other repos have.
* Clean up some imports in `src/encoded/__init__.py` to be ordered in a more readable way and to not use multi-line imports where not needed.

### CODE REVIEW

**Comment by j1z0** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/4dn/fourfront/pullRequest?prid=5266059&bid=17250980)

**Comment by j1z0** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/4dn/fourfront/pullRequest?prid=5266059&bid=17250980)

**Comment by j1z0** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/4dn/fourfront/pullRequest?prid=5266059&bid=17250980)

**Comment by j1z0** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/4dn/fourfront/pullRequest?prid=5266059&bid=17250980)

**Comment by netsettler** [comment]
@willronchetti , you said on slack that you had looked the substantive part of this PR over and were just waiting for a PR to approve, so I'm going to go ahead on the strength of that and do a merge. But please make a formal after-the-fact approval, or make comments on what was the problem and we can issue a follow-up change for immediate correction.

**Pull request merged**
