### PR TITLE
Finally use dcicutils.deployment_utils (C4-146)

### PR DESCRIPTION
**Pull request by netsettler**
This pulls the strings on all the scaffolding.

I have also merged some corrections from other branches that dealt with the handling of the indexing options and the display of that on the health page, as well as adding uptime information on the health page.

### CODE REVIEW

**Comment by netsettler** [comment]
OK, previewing what I’ll do to test the buckets. I am adding a thing in the code that tests the constructed files where you can add a line checker.
```
        old_content = old_output.getvalue()
        new_content = new_output.getvalue()
        problems = []
        if line_checker:
            for raw_line in io.StringIO(new_content):
                line = raw_line.rstrip()
                problem = line_checker(line)
                if problem:
                    problems.append(problem)
            assert problems == [], "Problems found:\n%s" % "\n".join(problems)
```
and then I’ll do something like this for blue, green, webprod, webprod2
```
            def prod_line_checker(line):
                if 'bucket =' in line:
                    fragment = 'fourfront-webprod'
                    if fragment not in line:
                        return "'%s' missing in '%s'" % (fragment, line)

            tester(ref_ini="blue.ini", bs_env="fourfront-blue", data_set="prod",
                   es_server="search-fourfront-blue-xkkzdrxkrunz35shbemkgrmhku.us-east-1.es.amazonaws.com:80",
                   line_checker=prod_line_checker)
```
I am not inserting a test tester, but I did test that this will find things. If edit it demand `'fourfront-oops'` I see:
```
                    problems.append(problem)
>           assert problems == [], "Problems found:\n%s" % "\n".join(problems)
E           AssertionError: Problems found:
E             'fourfront-oops' missing in 'file_upload_bucket = elasticbeanstalk-fourfront-webprod-files'
E             'fourfront-oops' missing in 'file_wfout_bucket = elasticbeanstalk-fourfront-webprod-wfoutput'
E             'fourfront-oops' missing in 'blob_bucket = elasticbeanstalk-fourfront-webprod-blobs'
E             'fourfront-oops' missing in 'system_bucket = elasticbeanstalk-fourfront-webprod-system'
E           assert ["'fourfront-...prod-system'"] == []
E             Left contains more items, first extra item: "'fourfront-oops' missing in 'file_upload_bucket = elasticbeanstalk-fourfront-webprod-files'"
E             Full diff:
E             + []
E             - ["'fourfront-oops' missing in 'file_upload_bucket = "
E             -  "elasticbeanstalk-fourfront-webprod-files'",
E             -  "'fourfront-oops' missing in 'file_wfout_bucket = "
E             -  "elasticbeanstalk-fourfront-webprod-wfoutput'",
E             -  "'fourfront-oops' missing in 'blob_bucket = "
E             -  "elasticbeanstalk-fourfront-webprod-blobs'",
E             -  "'fourfront-oops' missing in 'system_bucket = "
E             -  "elasticbeanstalk-fourfront-webprod-system'"]

deploy/tests/test_generate_production_ini.py:345: AssertionError
```
That’s the kind of thing you’re wanting, right?

**Comment by netsettler** [comment]
I got verbal confirmation from @willronchetti on that test. At some point I'll copy that change down to dcicutils but I think we're good here. If this passes tests, I'll go ahead with the merge.

**Comment by netsettler** [comment]
Actually, good catch on the merge down.  This PR actually doesn't modify the package.json or package-lock.json from master. Rather, it restored it from an intermediate version that an intermediate branch I was building from had done. But I'm trying at this point to just bypass that branch so have adjusted this PR to merge straight to master, and you can now see those files are not implicated.

**Comment by j1z0** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 6
           

Complexity increasing per file
==============================
- src/encoded/tests/test_root.py  7
         

Complexity decreasing per file
==============================
+ deploy/generate_production_ini.py  -18
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/4dn/fourfront/pullRequest?prid=5448834&bid=17866769)

**Comment by j1z0** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 6
           

Complexity increasing per file
==============================
- src/encoded/tests/test_root.py  7
         

Complexity decreasing per file
==============================
+ deploy/generate_production_ini.py  -18
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/4dn/fourfront/pullRequest?prid=5448834&bid=17866769)

**Comment by j1z0** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 6
           

Complexity increasing per file
==============================
- src/encoded/tests/test_root.py  7
         

Complexity decreasing per file
==============================
+ deploy/generate_production_ini.py  -18
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/4dn/fourfront/pullRequest?prid=5448834&bid=17866769)

**Comment by j1z0** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 6
           

Complexity increasing per file
==============================
- src/encoded/tests/test_root.py  7
         

Complexity decreasing per file
==============================
+ deploy/generate_production_ini.py  -18
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/4dn/fourfront/pullRequest?prid=5448834&bid=17866769)

**Pull request merged**
