### PR TITLE
vitessce upgrade from 1.1.20 to 2.0.3

### PR DESCRIPTION
**Pull request by gsabanci**
Trello: https://trello.com/c/h3HmI5un

### CODE REVIEW

**Review by Bianca-Morris — COMMENTED** [review]
Ran into some errors with this; not sure if you all are having this issue. I started by clearing my `node_modules` and `package-lock.json`, then did `npm install && npm install && npm dedupe && npm run dev-quick`. However, this keeps erroring out. I've gotten a couple of different ones pre-and-post running `make clean && make build`:

```
[09:53:27] Starting 'doWebpack'...
Opened webpack.config.js with env: quick & mode: development
[09:53:35] 'doWebpack' errored after 8.54 s
[09:53:35] Error: [BABEL]: Cannot find module '../lib/statuses'
Require stack:
- /Users/bmorris/projects/fourfront/node_modules/caniuse-lite/dist/unpacker/feature.js
- /Users/bmorris/projects/fourfront/node_modules/browserslist/node.js
- /Users/bmorris/projects/fourfront/node_modules/browserslist/index.js
- /Users/bmorris/projects/fourfront/node_modules/@babel/helper-compilation-targets/lib/index.js
- /Users/bmorris/projects/fourfront/node_modules/@babel/plugin-proposal-object-rest-spread/lib/index.js
- /Users/bmorris/projects/fourfront/node_modules/@babel/core/lib/config/files/module-types.js
- /Users/bmorris/projects/fourfront/node_modules/@babel/core/lib/config/files/configuration.js
- /Users/bmorris/projects/fourfront/node_modules/@babel/core/lib/config/files/index.js
.... (etc)
```

and 

```
[10:41:33] Starting 'doWebpack'...
Opened webpack.config.js with env: quick & mode: development
[10:41:34] 'doWebpack' errored after 1.5 s
[10:41:34] Error: [BABEL]: Cannot find module 'caniuse-lite/dist/unpacker/agents'
Require stack:
- /Users/bmorris/projects/fourfront/node_modules/browserslist/index.js
- /Users/bmorris/projects/fourfront/node_modules/@babel/helper-compilation-targets/lib/index.js
- /Users/bmorris/projects/fourfront/node_modules/@babel/plugin-proposal-object-rest-spread/lib/index.js
- /Users/bmorris/projects/fourfront/node_modules/@babel/core/lib/config/files/module-types.js
- /Users/bmorris/projects/fourfront/node_modules/@babel/core/lib/config/files/configuration.js
- /Users/bmorris/projects/fourfront/node_modules/@babel/core/lib/config/files/index.js
.... (etc0
```

**Comment by utku-ozturk** [comment]
@Bianca-Morris  running `npm run dev-quick` may work after `npm install && npm install && npm install && npm dedupe && npm audit fix`.

**Comment by utku-ozturk** [comment]
I have tested in local and mastertest, it looks good to me.

Screen Shot 2023-03-26 at 21 26 00

**Review by utku-ozturk — APPROVED** [review]
I have tested in local and mastertest, it looks good to me.

Screen Shot 2023-03-26 at 21 26 00

**Pull request merged**
