### PR TITLE
Legacy File's QC Summary Codes Removed

### PR DESCRIPTION
**Pull request by utku-ozturk**
**PS:** Pls also check the related [Foursight PR](https://github.com/4dn-dcic/foursight/pull/398) to remove schema updates 

**Trello:** https://trello.com/c/S8oyoOhO

**Background:** https://github.com/4dn-dcic/fourfront/pull/1326

### CODE REVIEW

**Review by alexkb0009 — APPROVED** [review]
Schema and inserts changes look good, would double check to make sure this field not being rendered in UI anywhere and good to merge I think.

**Comment by aschroed** [comment]
I believe this is the search that will find existing files that have values in this field:
https://data.4dnucleome.org/search/?quality_metric_summary.title%21=No+value&type=File&status=deleted&status%21=No+value

If someone can confirm that this is the case then I have a script that can do the job relatively quickly.

**Comment by utku-ozturk** [comment]
> I believe this is the search that will find existing files that have values in this field:
> https://data.4dnucleome.org/search/?quality_metric_summary.title%21=No+value&type=File&status=deleted&status%21=No+value
> 
> If someone can confirm that this is the case then I have a script that can do the job relatively quickly.

@aschroed Yes, I confirm. the search query above lists all files having qcs.

**Comment by aschroed** [comment]
OK I will delete fields when I am back in the office on Tuesday.

**Comment by aschroed** [comment]
@utku-ozturk the obsolete fields have now been deleted.

**Pull request merged**
