### PR TITLE
Change permissions and status for MicroscopeConfiguration

### PR DESCRIPTION
**Pull request by andreacosolo**
- keep only a few statuses: released, released to project, draft, deleted
- only admins can change status
- everyone who is logged in can create a new item (unchanged in this PR)
- 'draft' is similar to 'in review by lab', but works also if a user is not submitting for a lab
- this item cannot have additional properties in general (but the `microscope` sub-object still can)

### CODE REVIEW

**Review by aschroed — APPROVED** [review]
Looks good to me. LMK if you want me to test out local.

**Review by utku-ozturk — APPROVED** [review]
Looks good to me. My only concern is about merging it into #1495 since microscope_configuration is now inherited from user_content. There will inevitably be some conflicts but it's not a big deal. https://github.com/4dn-dcic/fourfront/blob/2aa5c058aebb75d9e5d6737f4be64f8b5a6767a1/src/encoded/schemas/microscope_configuration.json#L15 and https://github.com/4dn-dcic/fourfront/blob/2aa5c058aebb75d9e5d6737f4be64f8b5a6767a1/src/encoded/types/user_content.py#L224

**Comment by aschroed** [comment]
@utku-ozturk was making microscope configuration inherit from UserContent basically for convenience - and now with the changes that are required for permissions no longer makes sense for the integration of micrometa V2 branch or were there other reasons to do so?

**Comment by andreacosolo** [comment]
Closing this PR since these changes have been replicated in another branch https://github.com/4dn-dcic/fourfront/commit/63efc462af6f1fad3433851bbb8eba939cd4c916

**Pull request closed without merging**
