### PR TITLE
New Supplementary Files Table in /browse View and Statistics Updates

### PR DESCRIPTION
**Pull request by utku-ozturk**
### /browse View

- New `supplementary files` table under Exp. Set row detail panel
- `Select All` button now includes supplementary files along with raw and processed files
- `Select All `button is converted into split button to select raw/procesed/supplementary files separately

Screen Shot 2024-07-08 at 10 35 48

Screen Shot 2024-07-08 at 10 38 42
 

### Submission Statistics

- New `Group By` options - Lab and Exp. Type - added
- Cumulative sum checkbox added to switch between individual bars and cumulative sum
- Preset and custom date range filter added

Screen Shot 2024-06-20 at 13 23 37

Screen Shot 2024-06-20 at 13 37 10

### Usage Statistics

- File downloads splitted into two charts (count and volume)
- Cumulative sum checkbox added to switch between individual bars and cumulative sum
- Previous 60 days added to date range options

Screen Shot 2024-06-20 at 13 37 10

### Misc

- server-side download tracking triggered via cURL was failing, the bug is fixed
- glitches in mobile view fixed
- chart headers style updated (background color may needs to be changed??)

### CODE REVIEW

**Comment by utku-ozturk** [comment]
[Port SMaHT statistics page's date range and cumulative sum filtering options of to 4DN](https://trello.com/c/BV3hdKKo/285-port-smaht-statistics-pages-date-range-and-cumulative-sum-filtering-options-of-to-4dn)

**Comment by utku-ozturk** [comment]
[server-side download ga4 tracking updates](https://trello.com/c/ZUglyO8t/286-server-side-download-ga4-tracking-updates)

**Review by aschroed — COMMENTED** [review]
On hotseat this looks good to me however I did notice one thing.
If I try to manually enter a date into the Custom date range when I get to the year I get:
"loading failed - please try again later"
Selecting from the calendar appears to work fine.

**Comment by utku-ozturk** [comment]
> On hotseat this looks good to me however I did notice one thing. If I try to manually enter a date into the Custom date range when I get to the year I get: "loading failed - please try again later" Selecting from the calendar appears to work fine.

@aschroed  sure, let me check the manual date editing shortly. Thanks for the review!

**Comment by utku-ozturk** [comment]
[Add new supplementary files table below raw and processed files tables in /browse details](https://trello.com/c/qzaCbxgk/284-add-new-supplementary-files-table-below-raw-and-processed-files-tables-in-browse-details)

**Review by Bianca-Morris — COMMENTED** [review]
Some things I noticed while playing with this on hotseat:
- Tooltip is not visible at the end of the graph https://gyazo.com/ea8fbebab22ad88543b71dbd0a625918
- Running into some issues with custom date ranges. Seems like if you select a custom start or end range, the graphs are blank regardless of what data should be there. You can switch back to a preset date range, though, and that will work.
- Needs error handling and/or some indication/warning for invalid custom date ranges. Right now, if you put in an invalid date range (start date is after end date, for instance) the graphs are blank. It seems there is an uncaught error, though, since if you then change it to a valid date range or one of the preset date ranges, the graphs no longer update.

Random side note:
- Device category is pretty cool - apparently some small number of people view 4DN on Smart TVs? Fascinating.

Some notes on the code:
- Still using `setTimeout` in a few places where it looks like it may not be necessary.

**Comment by utku-ozturk** [comment]
[Enable selecting all files by its source (raw/processed/supplementary) in /browse view](https://trello.com/c/y2c1KQwz/305-enable-selecting-all-files-by-its-source-raw-processed-supplementary-in-browse-view)

**Comment by RahiNav** [comment]
Hi @utku-ozturk, I observed:
1. that when I selected "All raw files" it excluded (-) the experiment-set which has both raw and processed files? Same when I deselect "All processed files" (screenshot attached). Is this intentional? 
2. When I select "raw files" I can see both [x] [-], when I select "processed files", I only see [-] (screenshot attached)
Screenshot 2024-07-08 at 12 17 48 PM
Screenshot 2024-07-08 at 12 21 19 PM

**Comment by utku-ozturk** [comment]
Hi @RahiNav, thanks for your review.

The checkboxes in the row header have three states (`unchecked`, `indeterminate` ([-]), and `checked`) to show whether "none," "some," or "all" files are selected, respectively. Regarding your filtered [results](http://fourfront-hotseat-1650461284.us-east-1.elb.amazonaws.com/browse/?experiments_in_set.experiment_type.display_title=RNA-seq&experimentset_type=replicate&type=ExperimentSetReplicate), when I clicked "Select All Raw Files" some experiment sets checkboxes get `checked` state since they have only raw files but lacks any processed files. On the other hand, experiment sets having `indeterminate` ([-]) state have raw and processed files, and even if all their raw files are selected, their processed files are still out of selection. If we select the processed files in addition to the raw files, the `indeterminate` state will turn into a `checked` state.

I am attaching
Screen Shot 2024-07-09 at 16 13 23
 a screenshot showing rows and files are expanded to visualize what I described above.

**Review by aschroed — APPROVED** [review]
This looks good to me.  I wonder if it might be worthwhile to have Shannon have a look at the new selection options - I get it (especially after your explanation) but see why Rahi added her comment about the selection so perhaps there may be a way to make this a little clearer but I don't see any blockers on this.

**Review by crfmc — COMMENTED** [review]
Tested this on [Hotseat](http://fourfront-hotseat-1650461284.us-east-1.elb.amazonaws.com/statistics#submissions). The supplementary files work great for me with the updated SPC version. Submission Statistics issues are due to Hotseat's DB snapshot, otherwise looks great.

**Review by crfmc — APPROVED** [review]

**Review by Bianca-Morris — COMMENTED** [review]
There seem to be a few issues with the stats page that I don't think Andy noticed. The 30-day view for usage statistics is failing to load: https://gyazo.com/3177ad97fadead00d55e73933a0fd91f. Also, the submission statistics page https://gyazo.com/9d19753b40fa84734b4b83386d1dc1ee presets also seem to be not loading properly. Maybe an issue with hotseat's data? Not sure.

As for the browse view changes, that looks really good to me. I think a lot of the things Andy mentioned are relatively small, and can probably be added/fixed in a future updated. But the stats issues should definitely be resolved before merge.

**Comment by utku-ozturk** [comment]
@Bianca-Morris thanks for the review! yeah, good catch! I've manually run GA4-to-TrackingItem since no foursight action is working to do this. Now, it should display the data.

On the other hand, unfortunately, hotseat’s db snapshot is outdated, maybe more than one year old. Since submission statistics are solely based on metadata, the date range filtering does not show data for most date presets.

> There seem to be a few issues with the stats page that I don't think Andy noticed. The 30-day view for usage statistics is failing to load: https://gyazo.com/3177ad97fadead00d55e73933a0fd91f. Also, the submission statistics page https://gyazo.com/9d19753b40fa84734b4b83386d1dc1ee presets also seem to be not loading properly. Maybe an issue with hotseat's data? Not sure.
> 
> As for the browse view changes, that looks really good to me. I think a lot of the things Andy mentioned are relatively small, and can probably be added/fixed in a future updated. But the stats issues should definitely be resolved before merge.

**Pull request merged**
