### PR TITLE
Code Split Edits

### PR DESCRIPTION
**Pull request by utku-ozturk**
Port of JS code splitting of CGAP to 4DN. ([Trello ticke](https://trello.com/c/0WnQhwMs)t)

### CODE REVIEW

**Review by alexkb0009 — CHANGES_REQUESTED** [review]
Looks good but we're missing the biggest edit here which is [this one](https://github.com/dbmi-bgm/cgap-portal/pull/268/files#diff-09c56b2bf95de2a608a36afef3b6893146a959d6739be0a154dc9c9f02d80f24).

Can you guys make this edit, then ensure the code-splitting is working by running `npm run dev-analyzed` and then make sure the resulting /build/report.html (or whatever the filename is) shows the bundles as being properly split out (and not part of bundle.js)? E.g. like the following image:

**Review by alexkb0009 — APPROVED** [review]
Good to merge if working on local and `npm run dev-analyzed` generates report of split-apart bundles.

**Comment by utku-ozturk** [comment]
> Good to merge if working on local and `npm run dev-analyzed` generates report of split-apart bundles.

@alexkb0009 sure, we have already run `npm run dev-analyzed` and it was ok but we'll double check it tomorrow morning as a first task.

**Comment by utku-ozturk** [comment]
@alexkb0009 have uploaded the report; if it looks ok, I'll merge shortly.

newBundle

**Pull request merged**
