### PR TITLE
React 18, Redux and Misc. Npm Packages Upgrade

### PR DESCRIPTION
**Pull request by utku-ozturk**
Although this pull request primarily covers the transition from React 17 to React 18, it also includes updates for Redux, Auth0, and other third-party integrations heavily used in the portal to versions compatible with React 18. (Trello [1](https://trello.com/c/WqGmNmPz) & [2](https://trello.com/c/WqGmNmPz))

### Upgrades:

- React v17 to v18
- Redux v4 to v5 (there are breaking changes in store and dispatchers. SPC is updated to support both new and legacy usage - [PR](https://github.com/4dn-dcic/shared-portal-components/pull/259))
- HiGlass (React 18-compatible)
- Vitessce (React 18-compatible)
- MicroMeta App (released a new stable beta version for 4DN)
- Auth0-Lock v11 to v12 (it was on the waitlist for a long time since v12 was not supporting React v17)
- Gulp.js v4 to v5
- React-workflow-viz (animation updates to eliminate findDOMNode errors)

### Misc:

- User Content updates to fix markdown, jsx, and HTML static section rendering ([Trello](https://trello.com/c/WqGmNmPz))
- Improve ExperimentSetDetailPane's raw/processed/supplementary file panels ([Trello](https://trello.com/c/F7syVXo8))

### CODE REVIEW

**Comment by utku-ozturk** [comment]
[4DN - React 18 Upgrade](https://trello.com/c/vtKt3hAN/317-4dn-react-18-upgrade)

**Comment by utku-ozturk** [comment]
[Experiment set details pane updates](https://trello.com/c/F7syVXo8/334-experiment-set-details-pane-updates)

**Comment by utku-ozturk** [comment]
[fix "findDOMNode is deprecated" warnings](https://trello.com/c/DgXooUhc/326-fix-finddomnode-is-deprecated-warnings)

**Comment by utku-ozturk** [comment]
[Display react-workflow-viz version in HealthView page](https://trello.com/c/FwURD7Ro/335-display-react-workflow-viz-version-in-healthview-page)

**Review by Onurcankaratay — APPROVED** [review]

**Pull request merged**
