### PR TITLE
Fix uninitialized variable in generate_ontologies.py

### PR DESCRIPTION
**Pull request by netsettler**
The variable `prefixes` was used without initialization in `src/encoded/commands/generate_ontologies.py`. The initialization of this variable was dropped in [Fourfront PR #1165](https://github.com/4dn-dcic/fourfront/pull/1165/files), but it is possible that this was inadvertent. I'm guessing that just restoring the old initialization (from [Fourfront PR #1165, original line 773](https://github.com/4dn-dcic/fourfront/pull/1165/files#diff-2e52506bee6e438b2b78fff4d9940d4aL773)) is the right thing.

This isn't urgent, as presumably this script is called seldom or never, but PyCharm gets worried about it and marks the file in red when I happen into it, so I just want to get it fixed at some point.

We'll need to bump the patch version in `pyproject.toml` before merging this.

Also, it appears there are unit tests for this file and even for the specific function `id_post_and_patch` but apparently they don't get to this code because the tests pass both before and after this proposed change. If there's a way to get that code tested, that would be helpful. I'm not sure what to put for that.

Also...

* Sarah also added [a small commit related to authentication](https://github.com/4dn-dcic/fourfront/pull/1342/commits/2a075807b95006dba704983c900793263ec1b581) that now rides along with this.

### CODE REVIEW

**Comment by j1z0** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/encoded/tests/test_generate_ontology.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/4dn/fourfront/pullRequest?prid=5767814&bid=18876540)

**Comment by aschroed** [comment]
I'd like Sarah to check this when she get's back but I think the adding back change is fine.  I tweaked and added a couple of tests that I think cover this bit.  The id_fields2patch is not explicitly covered and there is some complexity in there that probably should be though I don't have the time right now to dive into that - these tests sent me down a bit of a rabbit hole as it was.

**Comment by netsettler** [comment]
@aschroed, it's fine to wait this until @sbreiff returns. Thanks for adding tests!

**Comment by j1z0** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/encoded/tests/test_generate_ontology.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/4dn/fourfront/pullRequest?prid=5767814&bid=18876540)

**Comment by j1z0** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/encoded/tests/test_generate_ontology.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/4dn/fourfront/pullRequest?prid=5767814&bid=18876540)

**Pull request merged**
